### ISSUE TITLE
(Warning) 'Firebase Warning' Using unspecified index. Your data will be downloaded and filtered on the client. Consider adding "IndexOn" "Contact_Number" at /app/User to your security rules for better performance.  

### ISSUE THREAD

**Issue by sarangvasishth** [dataoneio/kommunity#8]

**Comment by amolivora** [comment]
"app":{
    	"MyCom" :{
      	"User" :{".indexOn" : ["Contact_Number"]}
  	
   }
 }
change in firebase rules

**Comment by amolivora** [comment]
"app":{
"parkar" :{
"User" :{".indexOn" : ["Contact_Number","City"]},
"Blocked_Users":{".indexOn":["Blocked_Number"]},
"Event details":{".indexOn":["Category","UserId"]},
"Joining_Requests":{".indexOn":["Contact_Number"]}
}
}
